 

trigger:
- master

pool:
  vmImage: ubuntu-latest

 
stages: 
- stage: TeraformValidate
  jobs:
   - job: TeraformValidateJob
     continueOnError: false
     steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifacts
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
          artifact: 'terraform-manifests-out'
          publishLocation: 'pipeline'
      - task: TerraformInstaller@0
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
    backendType: 'azurerm'
    backendServiceArm: 'terraform-aks-azurerm-svc-con'
    allowTelemetryCollection: false
      